### ISSUE TITLE
Add support for submodules

### ISSUE THREAD

**Issue by mcmurrym** [pluralsight/git-switch-electron#16]
Currently the git post-commit-hook isn't applied to submodules, it would be really nice to have this feature to keep the author committer structure the same.

**Comment by parkerholladay** [comment]
@mcmurrym, I suppose we could recursively scan the git repo provided and see if there are other `.git` directories below the root. Though, just curious, have you tried specifying the root repo and submodules as independent git repos in `git-switch`? I'd like to know if that isn't working for some reason.

**Comment by mcmurrym** [comment]
yeah add the repo in git-switch doesn't work because (and this is why you couldn't just crawl) the .git dir of the submodule is located in .git/modules/MySubModule

**Comment by parkerholladay** [comment]
Gotcha. It's been a _really_ long time since I've used sub modules because I remember them being kind of a pain. But, I can look into that when I have some free time.
