### ISSUE TITLE
Running the app via npm breaks auto-rotation

### ISSUE THREAD

**Issue by jimboslicethat** [pluralsight/git-switch-electron#20]
Not sure if its a problem with just my machine. But If I startup the app using `npm run start`, or `npm run start:dev` I get the following runtime error when auto rotation happens.

```
Error Launching App:

Unable to find Electron app at /Users/jameswalsh/dev/channels/rotate

Cannot find module '/Users/jameswalsh/dev/channels/rotate'
```

* Do I need to reinitialize my repos since auto-rotation changes have been made?
* I should also add this does not happen when I package up the app and run it from the desktop instead of the command line.

**Comment by KaidenR** [comment]
@jimboslicethat Parker just pushed up a commit this morning to disable auto-rotate when running locally via npm. Do you have that commit?

**Comment by jimboslicethat** [comment]
I pulled before submitting this issue. I wonder if I just need to re-initialize the repos? Does that seem like it would be a thing I would need to do @parkerholladay?

**Comment by parkerholladay** [comment]
@jimboslicethat, have you tried since Thursday?
