### ISSUE TITLE
Finder opens behind the UI when using the "Add Repos" button

### ISSUE THREAD

**Issue by jimboslicethat** [pluralsight/git-switch-electron#33]
![git-switch-bug](https://user-images.githubusercontent.com/8390638/46041430-04240480-c0d0-11e8-8f08-22daf22e5e11.gif)

**Comment by parkerholladay** [comment]
Interesting. On windows and linux, git-switch disappears when you click `Add repos`

**Comment by jimboslicethat** [comment]
Whelp. Never mind. This is only happening in dev mode. Think for now Ill close the issue but probably something for us to look at eventually.
