### ISSUE TITLE
host is not configurable

### ISSUE THREAD

**Issue by NeilSorensen** [pluralsight/git-switch-electron#48]
One of the things that git-switch changes is the `.ssh/config`. Currently, it only sets the ssh IdentityFile for the github host.

It would be nice if we could configure it to use alternate hosts. I'll work on a pull request soon...

**Comment by NeilSorensen** [comment]
Apparently I can't link the pull request, but here it is: https://github.com/pluralsight/git-switch-electron/pull/49

**Comment by parkerholladay** [comment]
Fixed by #49

**Comment by parkerholladay** [comment]
Released in [v1.5.0](https://github.com/pluralsight/git-switch-electron/releases/tag/1.5.0)
